# Generated by Django 2.2.4 on 2021-01-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0002_auto_20210125_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='tasksAssociated', to='taskManager.Category'),
        ),
    ]
