# Generated by Django 2.2.4 on 2021-01-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0003_auto_20210125_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(related_name='tasksAssociated', to='taskManager.Category'),
        ),
    ]
